# Generated by Django 4.1.4 on 2023-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_members_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField()),
                ('is_right_choice', models.BooleanField(default=False)),
                ('choice', models.CharField(max_length=50)),
                ('attemptsleft', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='User',
        ),
    ]
